name: issue_publisher

on:
  issues:
    types: [opened, edited, deleted, labeled, unlabeled]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f build/requirements.txt ]; then pip install -r build/requirements.txt; fi
    - name: Run python file
      run: |
        python build/publisher.py
      env:
        TOKEN: ${{ secrets.TOKEN }}
